import Image from "next/image";
import {company} from "@/content/company";
import {brand} from "@/content/brand";
import {orderedProducts} from "@/content/products";
import {trustLinks} from "@/content/navigation";
import {Button,SectionHeader,Card,TrustLink,Statement} from "@/components/ui";
import {ProductCard} from "@/components/ProductCard";
import {pageMetadata} from "@/lib/seo";
export const metadata=pageMetadata(company.name,company.description,"/");
export default function Home(){const featured=orderedProducts().filter(p=>p.featured);return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Organization",name:company.name,url:company.domain,slogan:company.tagline}).replace(/</g,"\\u003c")}}/>
<section className="hero hero-technical">{brand.earthSunrise&&<Image className="hero-earth" src={brand.earthSunrise} alt={brand.heroAlt} fill priority sizes="100vw"/>}<div className="hero-shade" aria-hidden="true"/><div className="hero-content container"><div className="hero-overline"><p className="eyebrow">LLRD TECHNOLOGIES</p><span className="technical-label">PEOPLE / TECHNOLOGY / CONNECTION</span></div><h1>Technology that<br/>connects<br/><em>what matters.</em></h1><div className="hero-bottom"><p>{company.description}</p><Button href="/products">Explore our products</Button></div><div className="hero-rule" aria-hidden="true"/><div className="hero-caption"><span>GLOBAL THINKING. HUMAN IMPACT.</span><span>EXPLORE LLRD <span aria-hidden="true">↓</span></span></div></div></section>
<section className="pillars-band"><div className="container pillar-names">{company.pillars.map((p,i)=><div key={p.name}><span className="index">0{i+1}</span><span>{p.name}</span></div>)}</div></section>
<section className="section container"><SectionHeader eyebrow="OUR PORTFOLIO" title="Different possibilities. Shared purpose."><TrustLink href="/products">All products</TrustLink></SectionHeader>{featured.length?<div className="card-grid">{featured.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="portfolio-empty"><div className="portfolio-number" aria-hidden="true">LLRD</div><div><p className="eyebrow">FEATURED PRODUCTS</p><h3>A place for what comes next.</h3><p>Discover LLRD applications here as they become available, with clear ways to access each one.</p><TrustLink href="/products">Explore the portfolio</TrustLink></div></div>}</section>
<section className="why-section"><div className="container split"><div><p className="eyebrow">WHY LLRD</p><h2>It starts with<br/><em>what matters to you.</em></h2></div><div><p className="lead">{company.why}</p><TrustLink href="/about">Get to know LLRD</TrustLink></div></div></section>
<section className="section container"><SectionHeader eyebrow="WHAT WE BUILD" title="Useful by design. Purposeful by nature."/><div className="card-grid">{company.categories.map((c,i)=><Card key={c.title}><span className="index">0{i+1}</span><h3>{c.title}</h3><p>{c.text}</p></Card>)}</div></section>
<section className="section container access-section"><div><p className="eyebrow">YOUR WAY IN</p><h2>Choose how<br/>you connect.</h2><p>Web and native apps are complementary ways to use LLRD products. Availability is shown for each application.</p><TrustLink href="/products">Find your product</TrustLink></div><div className="access-list">{[{n:"01",title:"On the web",text:"Open available web applications directly from your browser."},{n:"02",title:"On iOS",text:"Find an App Store download when a product offers an iOS app."},{n:"03",title:"On Android",text:"Find a Google Play download when a product offers an Android app."}].map(x=><div key={x.n}><span className="index">{x.n}</span><div><h3>{x.title}</h3><p>{x.text}</p></div><span aria-hidden="true">↗</span></div>)}</div></section>
<section className="trust-section"><div className="container"><p className="eyebrow">BUILT ON TRUST</p><Statement>Connection begins<br/>with confidence.</Statement><p>A clear place to find privacy, security and legal information for LLRD and its products.</p><div className="trust-links">{trustLinks.map(l=><TrustLink key={l.href} href={l.href}>{l.label}</TrustLink>)}</div></div></section>
</>;}
