"use client";
import Link from "next/link";
import {useEffect,useState,type FormEvent} from "react";
import type {Product} from "@/content/products";
import {ProductPlatformCTA} from "./ProductPlatformCTA";
export function AIDiscovery({products}:{products:readonly Product[]}){
 const [available,setAvailable]=useState(false),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("Checking AI availability…"),[ids,setIds]=useState<string[]>([]);
 useEffect(()=>{const controller=new AbortController();fetch("/api/discovery/ai",{signal:controller.signal}).then(r=>r.json()).then(p=>{setAvailable(p.available===true);setMessage(p.available?"":"AI discovery is not connected yet. Use the guided choices below.");}).catch(()=>{if(!controller.signal.aborted)setMessage("AI discovery is unavailable. Use the guided choices below.");});return()=>controller.abort();},[]);
 async function submit(e:FormEvent){e.preventDefault();if(!available||busy)return;setBusy(true);setIds([]);setMessage("");try{const r=await fetch("/api/discovery/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query}),signal:AbortSignal.timeout(25000)});const p=await r.json();if(!r.ok){setMessage(p.message);return;}setIds(p.ids);setMessage(p.ids.length?"Suggested matches from the LLRD portfolio. Review each product’s details and availability.":"No matching product to share yet. Try the guided choices or explore all products.");}catch{setMessage("AI discovery is unavailable. Try the guided choices below.");}finally{setBusy(false);}}
 return <details className="ai-discovery"><summary>✧ Tell us what you’re looking for <span>AI discovery</span></summary><form onSubmit={submit}><label htmlFor="ai-query">What would you like help with?</label><textarea id="ai-query" rows={3} maxLength={600} minLength={5} required disabled={!available} value={query} onChange={e=>setQuery(e.target.value)} placeholder="For example: I want to preserve my family’s stories."/><p>AI responses may be inaccurate or incomplete and should be independently verified when important. Do not submit information you are not authorized to disclose. Your description is sent to OpenAI only when you select Find matches. Please omit personal or confidential information. <Link href="/privacy">Privacy</Link> · <Link href="/ai-policy">Learn about LLRD AI</Link></p><button className="button" disabled={!available||busy}>{busy?"Finding matches…":"Find matches →"}</button><p role="status">{message}</p></form>{products.filter(p=>ids.includes(p.id)).map(p=><article className="ai-match" key={p.id}><h3>{p.name}</h3><p>{p.shortDescription}</p><a className="text-link" href={"/products/"+p.slug}>Explore {p.name} →</a><ProductPlatformCTA product={p} headingLevel={4}/></article>)}</details>;
}
