import {notFound} from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import {getProduct,orderedProducts} from "@/content/products";
import {campaigns} from "@/content/campaigns";
import {publicCampaign} from "@/lib/campaigns";
import {safeHttps} from "@/lib/platforms";
import {pageMetadata} from "@/lib/seo";
import {ProductPlatformCTA} from "@/components/ProductPlatformCTA";
import {ProductCard} from "@/components/ProductCard";
import {Card,MediaPanel,TrustLink} from "@/components/ui";
import {ViewEvent,TrackedLink} from "@/components/TrackedLink";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=getProduct(slug);return p?pageMetadata(p.name,p.shortDescription,"/products/"+p.slug):{};}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=getProduct(slug);if(!p)notFound();const related=orderedProducts().filter(x=>x.id!==p.id).slice(0,3);const links=campaigns.filter(c=>c.productId===p.id&&publicCampaign(c));return <div className="container"><ViewEvent event="product_viewed" productId={p.id}/><section className="page-intro"><Link className="breadcrumb" href="/products">← All products</Link><p className="eyebrow">{p.category}</p>{p.logo&&<Image src={p.logo} alt={p.name+" logo"} width={160} height={80} unoptimized/>}<h1>{p.name}</h1><p className="lead">{p.tagline}</p><p>{p.shortDescription}</p><ProductPlatformCTA product={p}/></section><div className="page-body"><MediaPanel src={p.heroImage} alt={p.name} placeholder="Product visual forthcoming."/><section className="product-section prose"><h2>Meet {p.name}.</h2><p>{p.longDescription}</p>{p.comingSoonMessage&&<p>{p.comingSoonMessage}</p>}{safeHttps(p.websiteUrl)&&<TrustLink href={safeHttps(p.websiteUrl)!}>Product website</TrustLink>}</section>{p.features.length>0&&<section className="product-section"><h2>What you can do</h2><div className="card-grid">{p.features.map(f=><Card key={f.title}><h3>{f.title}</h3><p>{f.description}</p></Card>)}</div></section>}<section className="product-section"><h2>A closer look</h2>{p.media.length?p.media.map(m=><MediaPanel key={m.src} src={m.src} alt={m.alt}/>):<MediaPanel alt="" placeholder="Product screenshots forthcoming."/>}</section><section className="product-section"><h2>Support and trust</h2><div className="link-row"><TrackedLink href={safeHttps(p.supportUrl)||"/products/"+slug+"/support"} event="support_clicked" productId={p.id}>Product support</TrackedLink>{(["privacy","legal","security","delete-account"] as const).map(key=><TrustLink key={key} href={safeHttps(key==="privacy"?p.privacyUrl:key==="legal"?p.legalUrl:key==="security"?p.securityUrl:undefined)||"/products/"+slug+"/"+key}>{key==="delete-account"?"Account deletion":key.charAt(0).toUpperCase()+key.slice(1)}</TrustLink>)}</div></section>{links.length>0&&<section className="product-section"><h2>Explore more</h2>{links.map(c=><TrustLink key={c.id} href={"/campaigns/"+c.slug}>{c.name}</TrustLink>)}</section>}{related.length>0&&<section className="product-section"><h2>More from LLRD</h2><div className="card-grid">{related.map(r=><ProductCard key={r.id} product={r}/>)}</div></section>}</div></div>;}